Upgrade to latest mypy to fix internal error
/home/runner/.cache/pypoetry/virtualenvs/langchain-visualizer-asnL2hpd-py3.10/lib/python3.10/site-packages/fastapi/openapi/models.py:281: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.991
/home/runner/.cache/pypoetry/virtualenvs/langchain-visualizer-asnL2hpd-py3.10/lib/python3.10/site-packages/fastapi/openapi/models.py:281: : note: please use --show-traceback to print a traceback when reporting a bug